### ISSUE TITLE
新浪微博5.0以上隐式声明Intent启动Service引发的问题

### ISSUE THREAD

**Issue by hjgang** [xyzlf/ShareSDK#10]
2017-07-03 16:43:15
App Version:1.0_1
OS version:6.0_23
Vendor:ZTE
Model:ZTE BV0720
CPU ABI:arm64-v8a
java.lang.RuntimeException: Unable to start activity ComponentInfo{xxxxx/com.xyzlf.share.library.ShareHandlerActivity}: java.lang.IllegalArgumentException: Service Intent must be explicit: Intent { act=com.sina.weibo.remotessoservice }
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2551)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2617)
	at android.app.ActivityThread.-wrap11(ActivityThread.java)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1473)
	at android.os.Handler.dispatchMessage(Handler.java:111)
	at android.os.Looper.loop(Looper.java:207)
	at android.app.ActivityThread.main(ActivityThread.java:5701)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:905)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:766)
Caused by: java.lang.IllegalArgumentException: Service Intent must be explicit: Intent { act=com.sina.weibo.remotessoservice }
	at android.app.ContextImpl.validateServiceIntent(ContextImpl.java:1281)
	at android.app.ContextImpl.bindServiceCommon(ContextImpl.java:1380)
	at android.app.ContextImpl.bindService(ContextImpl.java:1358)
	at android.content.ContextWrapper.bindService(ContextWrapper.java:604)
	at com.sina.weibo.sdk.auth.sso.SsoHandler.bindRemoteSSOService(SsoHandler.java:329)
	at com.sina.weibo.sdk.auth.sso.SsoHandler.authorize(SsoHandler.java:182)
	at com.sina.weibo.sdk.auth.sso.SsoHandler.authorize(SsoHandler.java:133)
	at com.xyzlf.share.library.channel.ShareByWeibo.share(ShareByWeibo.java:94)
	at com.xyzlf.share.library.ShareHandlerActivity.onCreate(ShareHandlerActivity.java:77)
	at android.app.Activity.performCreate(Activity.java:6270)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1113)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2504)
	... 9 more

**Comment by xyzlf** [comment]
0.0.8aar已经解决~
