### ISSUE TITLE
升级android 8.0后三星 s7 造成应用crash

### ISSUE THREAD

**Issue by zj2050** [xyzlf/ShareSDK#21]
请协助修复，谢谢

**Comment by xyzlf** [comment]
crash日志嘞？

**Comment by zj2050** [comment]
@xyzlf 谢谢

`
 --------- beginning of crash
08-20 15:46:54.079 17864-17864/
    java.lang.RuntimeException: Unable to start activity java.lang.IllegalStateException: Only fullscreen opaque activities can request orientation
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2957)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3032)
        at android.app.ActivityThread.-wrap11(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1696)
        at android.os.Handler.dispatchMessage(Handler.java:105)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6944)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)
     Caused by: java.lang.IllegalStateException: Only fullscreen opaque activities can request orientation
        

`

**Comment by xyzlf** [comment]
com.xyzlf.share:sharesdk:0.0.11
你升级一下试试，我手上没有这部手机，如果还有问题，我在修改下。

**Comment by zj2050** [comment]
@xyzlf 可以了，谢谢
