### ISSUE TITLE
回调 statue = 4 ,无法打开微信， 在fragment下调用直接crash

### ISSUE THREAD

**Issue by zj2050** [xyzlf/ShareSDK#26]
Android 8.0
肯定用的正式的， 但程序在横屏状态下

在Activity 和 fragment 页面下都能调起分享对话框， 在 activity 下选择分享微信， 返回statue = 4 ，没死机但无法打开微信， 在fragment 下面 没有回调 直接死机了

打开分享到对话框后 跟踪到的代码：
I/CrashReport: Set native info: isAppForeground(false)
D/ViewRootImpl@77dc516[MentalMainActivity]: MSG_WINDOW_FOCUS_CHANGED 0
D/CrashReport: >>> com.xyzlf.share.library.ShareDialogActivity onCreated <<<
W/Bundle: Key extra_share_data expected Bundle but value was a com.xyzlf.share.library.bean.ShareEntity.  The default value <null> was returned.
W/Bundle: Attempt to cast generated internal exception:
    java.lang.ClassCastException: com.xyzlf.share.library.bean.ShareEntity cannot be cast to android.os.Bundle
        at android.os.Bundle.getBundle(Bundle.java:871)
        at android.content.Intent.getBundleExtra(Intent.java:7972)
        at com.xyzlf.share.library.ShareDialogActivity.onCreate(ShareDialogActivity.java:45)
        at android.app.Activity.performCreate(Activity.java:7183)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1220)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2910)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3032)
        at android.app.ActivityThread.-wrap11(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1696)
        at android.os.Handler.dispatchMessage(Handler.java:105)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6944)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)
W/System.err: android.content.pm.PackageManager$NameNotFoundException: com.tencent.mobileqq
        at android.app.ApplicationPackageManager.getPackageInfoAsUser(ApplicationPackageManager.java:298)
        at android.app.ApplicationPackageManager.getPackageInfo(ApplicationPackageManager.java:269)
        at com.xyzlf.share.library.util.ChannelUtil.isAppInstall(ChannelUtil.java:26)
        at com.xyzlf.share.library.util.ChannelUtil.isQQInstall(ChannelUtil.java:48)
        at com.xyzlf.share.library.ShareDialogActivity.initChannelData(ShareDialogActivity.java:99)
W/System.err:     at com.xyzlf.share.library.ShareDialogActivity.onCreate(ShareDialogActivity.java:79)
        at android.app.Activity.performCreate(Activity.java:7183)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1220)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2910)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3032)
        at android.app.ActivityThread.-wrap11(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1696)
        at android.os.Handler.dispatchMessage(Handler.java:105)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6944)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)
D/CrashReport: >>> com.xyzlf.share.library.ShareDialogActivity onResumed <<<
I/CrashReport: Set native info: isAppForeground(true)
D/ViewRootImpl@7b87460[ShareDialogActivity]: setView = DecorView@f3efd19[ShareDialogActivity] TM=true MM=false
V/InputMethodManager: Not IME target window, ignoring
D/ViewRootImpl@7b87460[ShareDialogActivity]: dispatchAttachedToWindow
V/Surface: sf_framedrop debug : 0x4f4c, game : false, logging : 0
D/ViewRootImpl@7b87460[ShareDialogActivity]: Relayout returned: old=[0,0][0,0] new=[720,313][1840,1126] result=0x7 surface={valid=true 3290238976} changed=true
D/OpenGLRenderer: eglCreateWindowSurface = 0xc254dd88
D/AbsListView:  in onLayout changed

**Comment by zj2050** [comment]
@xyzlf 请协助
